
environment:
  - nodejs_version: '10'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install --global npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install

build: off

shallow_clone: true

test_script:
  - node --version
  - npm --version
  - npm test

cache:
  - '%APPDATA%\npm-cache'
